name: Iroha2-java pull requests workflow

on:
  pull_request:
    branches: [ iroha2-dev, iroha2-main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle with configuration cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2
      - name: Build with Gradle
        run: ./gradlew build --configuration-cache --info
      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: /home/runner/work/iroha-java/iroha-java/**/index.html
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
